# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: serviceConnection
  value: 'myBicepProjectSP'  
- group: Tags

jobs:
- job: Development
  displayName: Development
  variables: 
    - group: Dev
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo $(storageAccountName)
        echo ${{variables.serviceConnection}}
        echo $(Project)

- job: Test
  displayName: Test
  dependsOn: Development
  variables: 
    - group: TestLib
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo $(storageAccountName)
        echo ${{variables.serviceConnection}}
        echo $(Project)
