# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  resourceGroup: 'rg-biceptest'

jobs:
  - job: Deploy
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'My Deploy'
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'myBicepProjectSP'
          subscriptionId: 'b46e8829-2695-4ed0-9df1-693b7ecdd53d'
          action: 'Create Or Update Resource Group'
          resourceGroupName: $(resourceGroup)
          location: 'Australia East'
          templateLocation: 'Linked artifact'
          csmFile: 'main.bicep'
          csmParametersFile: 'main.parameters.json'
          deploymentMode: 'incremental'
  - job: Cleanup
    dependsOn: Deploy
    steps:
      - task: AzureCLI@2
        displayName: 'Cleaunp Resources'
        inputs:
          azureSubscription: 'myBicepProjectSP'
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: 'az group delete --name $(resourceGroup) --yes'