
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: serviceConnection
  value: 'BicepDevOps'
- name: location
  value: 'australiasoutheast'
- name: templateFilePath
  value: '$(Pipeline.Workspace)/drop/deployAzureDataFactory.bicep'
- name: parametersFolderPath
  value: '$(Pipeline.Workspace)/drop'  
- group: Tags

stages:
- stage: BuildandPublish
  jobs:
  - job: Build
    displayName: 'Build Artifacts'
    steps:
    - script: |
        az bicep build --file 'deployAzureDataFactory.bicep'

  - job: Publish
    displayName: 'Publish Artifacts'
    dependsOn: Build
    steps:
    - task: CopyFiles@2
      displayName: 'Copy files'
      inputs:
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - publish: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Publish files'
      artifact: drop

- stage: Preview
  jobs:
  - job: Validate
    displayName: 'Validate Bicep code'
    variables: 
      - group: Dev    
    steps:
    - download: current
      artifact: drop
    - task: AzureCLI@2
      name: RunPreflightValidation
      displayName: 'Run preflight validation'
      inputs:
        azureSubscription: ${{variables.serviceConnection}}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group validate \
          --resource-group 'RG-DEV' \
          --template-file ${{variables.templateFilePath}} \
          --parameters @${{variables.parametersFolderPath}}/deployAzureDataFactoryParameters.json \
          --parameters sequence=$(Sequence) \
          --name $(Build.BuildNumber)      

- stage: Deploy
  jobs:
  - deployment: DeployInfrastructure
    displayName: Deploy infrastructure 
    variables: 
      - group: Dev        
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop
            - task: AzureCLI@2
              name: DeployBicepFile
              displayName: Deploy Bicep file
              inputs:
                azureSubscription: ${{variables.serviceConnection}}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment group create \
                  --resource-group 'RG-DEV' \
                  --template-file ${{variables.templateFilePath}} \
                  --parameters @${{variables.parametersFolderPath}}/deployAzureDataFactoryParameters.json \
                  --parameters sequence=$(Sequence) 